# Site settings
title: Alex Ives
email: alex@ives.mn
description: "% Enthusiast."
baseurl: ""
url: ""
github_username:  alexives
twitter_username: alexeives
linkedin_profile: https://www.linkedin.com/pub/alexander-ives/42/916/253
paginate: 6

# Build settings
markdown: kramdown
permalink: pretty

gems:
  - jekyll-paginate
