# Site settings
title: Alex Ives
email: alex@ives.mn
description: "% Enthusiast."
baseurl: ""
url: ""
github_username:  alexives
twitter_username: alexeives
linkedin_profile: https://www.linkedin.com/pub/alexander-ives/42/916/253
paginate: 6

# Build settings
markdown: kramdown
permalink: pretty

gems:
  - jekyll-paginate
prose:
  ignore: ['_includes', 'Gemfile', '_config.yml', '.gitignore', '.ruby-version', '.gitlab-ci.yml', 'CNAME', 'feed.xml', 'keybase.txt', 'README.md', '_layouts', '_site', 'css']
  media: 'images'
  metadata:
    _posts:
      - name: layout
        field:
          element: select
          label: Layout
          value: post
          options:
            - name: 'Blog Post'
              value: 'post'
            - name: 'Project Post'
              value: 'project'
      - name: title
        field:
          element: text
          label: Post Title
          placeholder: A title for your post
      - name: date
        field:
          element: text
          label: Post Date
      - name: categories
        field:
          element: text
          label: Post Categories
          placeholder: fruit, beer, keyboards
      - name: author
        field:
          element: text
          label: Post Author
          value: Alex Ives
      - name: seqnext
        field:
          element: text
          label: Next article in series
      - name: seqprevious
        field:
          element: text
          label: Previous article in series
