# Site settings
title: Alex Ives
email: alex@ives.mn
description: "Computer Enthuseist."
baseurl: ""
url: "http://alexives.github.io"
github_username:  alexives
twitter_username: alexeives

# Build settings
markdown: kramdown
permalink: pretty
