# Site settings
title: Alex Ives
email: alex@ives.mn
description: "% Enthuseist."
baseurl: ""
url: ""
github_username:  alexives
twitter_username: alexeives

# Build settings
markdown: kramdown
permalink: pretty
